- name: Download Process Exporter
  get_url:
    url: "{{ process_exporter_url }}"
    dest: "/tmp/process-exporter-{{ process_exporter_version }}.tar.gz"

- name: Create group for process_exporter
  group:
    name: "{{ process_exporter_group }}"
    state: present

- name: Create user for process_exporter
  user:
    name: "{{ process_exporter_user }}"
    group: "{{ process_exporter_group }}"
    shell: /bin/false
    system: true

- name: Create directory for Process Exporter
  file:
    path: /etc/process_exporter
    state: directory
    owner: "{{ process_exporter_user }}"
    group: "{{ process_exporter_group }}"
    mode: '0755'

- name: Unpack Process Exporter
  unarchive:
    src: "/tmp/process-exporter-{{ process_exporter_version }}.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: List contents of unpacked directory
  #command: ls -l /tmp/process-exporter-{{ process_exporter_version }}.linux-386
  command: ls -l /tmp/process-exporter-{{ process_exporter_version }}.{{ process_exporter_Linux }}
  register: unpacked_files

- debug:
    var: unpacked_files.stdout_lines

- name: Move Process Exporter binary
  command: mv /tmp/process-exporter-{{ process_exporter_version }}.{{ process_exporter_Linux }}/process-exporter /usr/bin/process-exporter
  args:
    creates: /usr/bin/process-exporter

#- name: Move Process Exporter binary
#  copy:
#    src: "/tmp/process-exporter-{{ process_exporter_version }}.linux-amd64/process-exporter"
#    dest: "/usr/bin/process-exporter"
#    owner: "{{ process_exporter_user }}"
#    group: "{{ process_exporter_group }}"
#    mode: '0755'


#- name: Configure Process Exporter
#  template:
#    src: process-exporter.yaml.j2
#    dest: "{{ process_exporter_config_file }}"
#    owner: "{{ process_exporter_user }}"
#    group: "{{ process_exporter_group }}"
#    mode: '0644'
- name: Copy Config
  copy:
    dest: "{{ process_exporter_config_file }}"
    src: ./templates/process-exporter.yaml
    


- name: Create Process Exporter systemd service
  copy:
    dest: "{{ process_exporter_service_file }}"
    content: |
      [Unit]
      Description=Process Exporter for Prometheus
      Documentation=https://github.com/ncabatoff/process-exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User={{ process_exporter_user }}
      Group={{ process_exporter_group }}
      Type=simple
      Restart=on-failure
      ExecStart=/usr/bin/process-exporter --config.path {{ process_exporter_config_file }} --web.listen-address=:9256

      [Install]
      WantedBy=multi-user.target

- name: Set permissions for service file
  file:
    path: "{{ process_exporter_service_file }}"
    mode: '0644'

- name: Reload systemd to recognize new service
  systemd:
    daemon_reload: yes

- name: Start Process Exporter service
  systemd:
    name: process_exporter
    state: started
    enabled: true

- name: Clean up installation files
  file:
    path: "/tmp/process-exporter-{{ process_exporter_version }}.tar.gz"
    state: absent
