---
- name: restart apache
  service:
    name: apache2
    state: restarted
  when: ansible_os_family == "Debian"

- name: restart apache (RedHat based)
  service:
    name: httpd
    state: restarted
  when: ansible_os_family == "RedHat"
