---
- name: restart apache
  service:
    name: apache2
    state: restarted
  when: ansible_os_family == "Debian"

- name: restart apache (RedHat based)
  service:
    name: httpd
    state: restarted
  when: ansible_os_family == "RedHat"

- name: Debug - Print OS Family and Distribution
  debug:
    msg: "OS Family: {{ ansible_os_family }}, Distribution: {{ ansible_distribution }}"
    
