---
- name: Install Apache
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"

- name: Install Apache (RedHat based)
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"


- name: Create index.html
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
  notify: restart apache

- name: Enable and start Apache
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Enable and start Apache (RedHat based)
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

#- name: Open port 80
#  ufw:
#    rule: allow
#    port: 80
#    proto: tcp
#  when: ansible_distribution != 'CentOS' and ansible_distribution != 'Red Hat Enterprise Linux Server' and ansible_distribution != 'Fedora' # UFW not installed by default in some RHEL-based distros, check it before running

- name: Check website availability
  uri:
    url: http://{{ ansible_host }}
    status_code: 200
    #retries: 3
    #delay: 5
  register: website_status  # Сохраняем результат проверки
    
- name: Wait for website to become available
  wait_for:
    timeout: 60
    state: started
    port: 80
  when: website_status.failed

- name: Debug
  debug: 
    msg: "{{ website_status.status }}"

- name: Fail if website is not reachable
  fail:
    msg: "Website is not reachable!"
  when: website_status is failed


