---
- hosts: all
  become: true
  roles:
    - webserver_setup

  tasks:
  - name: Debug - Print OS Family and Distribution
    debug:
      msg: "OS Family: {{ ansible_os_family }}, Distribution: {{ ansible_distribution }}"
    
 # - name: remove
 #   apt:
 #     name: apache2
 #     state: absent
 #   tags: remove